from .base import Verbalizer
from .manual_verbalizer import ManualVerbalizer
from .one2one_verbalizer import One2oneVerbalizer
from .soft_verbalizer import SoftVerbalizer
from .automatic_verbalizer import AutomaticVerbalizer
from .contextual_verbalizer import ContextualVerbalizer
from .knowledgeable_verbalizer import KnowledgeableVerbalizer
from .label_embedding import LabelEmbedVerbalizer